name: MGSkyWars
main: com.comze_instancelabs.mgskywars.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [InstanceLabs,TheMrQuake,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   sw:
      description: Main command
      usage: /sw [action]
      aliases: [skywars, mgskywars]
